

services:
  hema-api-service:
    build: .
    image: hema-api-image:latest
    container_name: hema-api-service
    ports:
      - "8001:3000"
    environment:
      - MONGO_URL=${MONGO_URL}
    restart: always