# 1. Base Image
FROM node:18-alpine

# 2. Work Directory
WORKDIR /app

# 3. Install Modules

COPY package*.json ./
RUN npm install

# 4. Copy Code
COPY . .


EXPOSE 3000

# 6. Run Command
CMD ["node", "hema.js"]